<a href="https://colab.research.google.com/github/wenyuesr/chinese-programmer-wrong-pronunciation/blob/master/HelloTensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow
- Tensor + Flow

In [5]:
import tensorflow as tf

tf.compat.v1.disable_eager_execution()

node1 = tf.constant([3.0, 5.0])
node2 = tf.constant([4.0, 6.0])
sum = tf.add(node1, node2)

# tf 1.0 with tf.Session() as sess:
# sess = tf.compat.v1.Session()
with tf.compat.v1.Session() as sess:
    print(sess.run(sum))

[ 7. 11.]


## 基础概念
- 张量 tensor
- 计算图 graph 节点 node 边 edge
- 算子 operation
- 会话 session - feed - fetch
- 变量 variable

### Graph

In [ ]:
import tensorflow as tf


tf.compat.v1.disable_eager_execution()

node1 = tf.constant([3.0, 5.0])
node2 = tf.constant([4.0, 6.0])

# 获取图 理解为内存空间
print(node1.graph)
print(node2.graph)
print(tf.compat.v1.get_default_graph())

sum = tf.add(node1, node2)

# tf 1.0 with tf.Session() as sess:
# sess = tf.compat.v1.Session()
with tf.compat.v1.Session() as sess:
    print(sess.run(sum))

[ 7. 11.]


### 每个程序有个默认图 上面演示打印出默认图 get_default_graph
- 下面是创建新图 tf.Graph() 并且使用


In [ ]:
# 创建一张新图
g = tf.Graph()
with g.as_default():
    b = tf.constant(123)

# 下面这句也可以用 with
# sess = tf.compat.v1.Session(graph = g)
with tf.compat.v1.Session(graph=g) as sess:
    # print(sess.run(node1)) # 一个程序定义多张图 每张图 有不同的节点
    print(b)
    print(sess.run(b)) # 默认跑 default 图 但是b在g图里面 graph=g 指定g图


Tensor("Const:0", shape=(), dtype=int32)
123


# Session
- 拥有并管理TensorFlow程序运行时的所有资源
- 客户端使用Session和TF系统交互
- 建立会话 -> 生成空图 -> 在Session中添加node和edge 形成一张图 -> execute

In [ ]:
# 测试 Session
node1 = tf.constant(123)
# 括号里面参数 显示结构
with tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(log_device_placement=True)) as sess:
    # 两种方式取出 node1 的值 第二种方式需要 with 上下文环境
    print(sess.run(node1))
    print(node1.eval())
# 关闭
# sess.close()

Device mapping:
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device

123
123


### 交互式Session tf.InteractiveSession()
- 一般用在 对话框 prompt cmd 中

## Feed 注入机制
- 程序执行的时候 不确定输入的是什么 提前“占个坑”
- 语法 placeholder提供占位符 run的时候通过feet_dict指定参数

In [ ]:
# None：不知道样本多少个 3：特征为三个
plt = tf.compat.v1.placeholder(tf.float32, [None, 3])
with tf.compat.v1.Session() as sess:
    # 数组数量（样本数）是None 所以 不局限于两个 但是特征值是 3
    print(sess.run(plt, feed_dict={plt: [[1, 2, 3], [4, 5, 6]]}))

[[1. 2. 3.]
 [4. 5. 6.]]


## Fetch 取回机制
- run() eval()

# Tensor 张量

- 是数据的载体
- 可以是任意维度的数据
- 在一个运行的graph中，她是一种流动在node之间的数据
- tensor 保存的是 张量 的数据结构 ： name+shape+type

## tensor的阶和数据类型

|阶|数学实例|Python|例子|
|-|-|-|-|
|0|纯量|只有大小|S = 483|
|1|向量|大小和方向|v = [1.1, 2.2]|
|2|矩阵|数据表|m=[[1,2,3],[4,5,6],[7,8,9]]|
|3|3阶张量|数据立体|t = [[[2],[4],[6],[8],[10],[12],[14],[16],[18]]]|
|n|n阶|...|...|

In [17]:
a = tf.constant(10)
b = tf.constant([1.0, 2.0])
c = tf.constant([[1, 2],[3, 4]])
d = tf.constant([[[1,2,3],[4,5,6],[7,8,9]]])

with tf.compat.v1.Session() as sess:
  print(sess.run(a))
  print(sess.run(b))
  print(sess.run(c))
  print(sess.run(d))


10
[1. 2.]
[[1 2]
 [3 4]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [15]:
print(tf.__version__)

2.3.0
